In [1]:
import numpy as np

In [2]:
P_1 = np.array([[1,2],[2,-1]])
P_2 = np.array([[1,3],[3,-1]])
P_3 = np.array([[-1,1.5],[1.5,1]])

These matrcies are symmetric and trace 0

In [3]:
print('P_1')
print(P_1)

print('P_2')
print(P_2)

print('P_3')
print(P_3)

P_1
[[ 1  2]
 [ 2 -1]]
P_2
[[ 1  3]
 [ 3 -1]]
P_3
[[-1.   1.5]
 [ 1.5  1. ]]


x satisfies
$x^TP_1x = x^TP_2x = 1$ and $x^TP_3x < 0$

In [4]:
x = np.array([1,0])
print('x',x)
print('x^TP_1x =', x.T@P_1@x)
print('x^TP_2x =', x.T@P_2@x)
print('x^TP_3x =', x.T@P_3@x)

x [1 0]
x^TP_1x = 1
x^TP_2x = 1
x^TP_3x = -1.0


$P_3 = QDQ^T$ where $Q$ is orthogonal and $D$ is diagonal

In [5]:
s, Q = np.linalg.eig(P_3)
D = np.diag(s)
print('Q is orthogonal:')
print('QQ^T= ')
print(Q@Q.T)
print('Q^TQ= ')
print(Q.T@Q)
print('D')
print(D)
print('P_3 = QDQ^T')
print(Q@D@Q.T)

Q is orthogonal:
QQ^T= 
[[1. 0.]
 [0. 1.]]
Q^TQ= 
[[1. 0.]
 [0. 1.]]
D
[[-1.80277564  0.        ]
 [ 0.          1.80277564]]
P_3 = QDQ^T
[[-1.   1.5]
 [ 1.5  1. ]]


so let $x_{new} = Q^Tx$

In [6]:
x_new = Q.T@x

Then $0> x_{new}^T D x_{new} = x^TP_3x$ by construction

In [7]:
x_new.T@D@x_new

-0.9999999999999996

But  $x_{new}^T P_1 x_{new} = x^TQP_1Q^Tx \neq x^TP_1x$ and $x_{new}^T P_1 x_{new} \neq x_{new}^T P_2 x_{new}$

In [8]:
x_new.T@P_1@x_new

2.2188007849009166

In [9]:
x_new.T@P_2@x_new

3.05085107923876