In [1]:
import numpy as np

In [68]:
def generate_trace_zero_constraints(dim, num_constraints):
    constraints = []
    for _ in range(num_constraints):
        M = np.random.randn(dim,dim)
        M = np.matmul(np.transpose(M),M)
        for i in range(dim):
            M[i,i] = 0
        i = np.random.randint(0,dim)
        M[i,i]=1
        j = np.random.randint(0,dim)
        while(i==j):
            j = np.random.randint(0,dim)
        M[j,j]=-1
        constraints.append(M)
    x = np.random.randn(dim,1)

    for i in range(len(constraints)):
        if np.matmul(np.transpose(x),np.matmul(constraints[i],x)) <0:
            constraints[i] = -1*constraints[i]
        elif np.matmul(np.transpose(x),np.matmul(constraints[i],x)) ==0:
            print('Oh no! Something evaluates to 0!')

    return constraints, x

In [15]:
def get_sigmoid_denom(x):
    return 1+np.exp(x)

In [85]:
def get_hessian_gradient_objective(dim, num_constraints):
    hessian = np.zeros((dim,dim))
    grad = np.zeros((dim,1))
    obj = 0
    
    constraints,x_true = generate_trace_zero_constraints(dim, num_constraints)
    x = np.random.randn(dim,1)
    for constraint in constraints:
        quad_form = np.matmul( np.matmul(np.transpose(x), constraint), x)
        denom = get_sigmoid_denom(quad_form)
        P_x = np.matmul(constraint, x)
        
        obj +=np.log(1+np.exp(-quad_form))
        grad += 2/denom * P_x
        hessian += 4*np.exp(quad_form) / (denom*denom)* np.matmul(P_x, np.transpose(P_x)) + 2/denom*constraint
    return hessian, grad, obj

In [75]:
def check_eigvalues(x):
    flag_pos = 0
    flag_neg = 0
    for i in range(len(x)):
        if x[i]>0:
            flag_pos = 1
        elif x[i]<0:
            flag_neg = 1
    if flag_pos ==1 and flag_neg ==1:
        print('indefinite')
    elif flag_neg ==0 and flag_pos == 1:
        print('PSD')
    else:
        print('NSD')

In [86]:
for _ in range(100):
    hessian, grad, obj = get_hessian_gradient_objective(3, 1)
    print(np.linalg.norm(grad), obj)
    eig_val = np.linalg.eig(hessian)[0]
    check_eigvalues(eig_val)

4.84337204049 [[ 4.7057585]]
indefinite
0.597663787551 [[ 0.09528587]]
indefinite
1.1311734864 [[ 0.07142594]]
indefinite
6.2367158851 [[ 4.1520704]]
indefinite
1.01976430524 [[ 0.51394412]]
indefinite
8.07733908788 [[ 2.29675712]]
indefinite
12.6372189161 [[ 8.58647051]]
indefinite
0.62807028934 [[ 0.85074964]]
indefinite
8.78047658664 [[ 3.42599169]]
indefinite
9.89782253603 [[ 4.85237893]]
indefinite
7.10826565347 [[ 2.05369062]]
indefinite
0.812368272012 [[ 0.11666677]]
indefinite
0.66290017431 [[ 0.27424009]]
indefinite
1.65010519815 [[ 0.49188199]]
indefinite
0.446813331935 [[ 0.08885392]]
indefinite
0.635376028631 [[ 0.59608492]]
indefinite
1.20082771332 [[ 0.15052026]]
indefinite
0.336196912945 [[ 0.07967325]]
indefinite
1.07326169208 [[ 0.30934952]]
indefinite
1.1369738062 [[ 0.42017643]]
indefinite
1.20180235263e-05 [[  7.79856386e-07]]
indefinite
1.32746201031e-06 [[  8.00486410e-08]]
indefinite
3.21303195358e-05 [[  2.61825814e-06]]
indefinite
1.25122973338 [[ 0.78157168]]


In [20]:
print(H)

[[ 0.08243715  0.01056687 -0.39957595]
 [ 0.01056687  1.70358463 -0.41482539]
 [-0.39957595 -0.41482539 -0.34190497]]


In [21]:
np.linalg.eig(H)

(array([-0.63572005,  0.29071878,  1.78911808]),
 array([[-0.47891259,  0.87626319,  0.05296753],
        [-0.15118096, -0.14176104,  0.97828837],
        [-0.86474681, -0.46050693, -0.20036546]]))